from __future__ import annotations

import io
import re
import zipfile
from pathlib import Path

PLUGIN_FOLDER = "calibretypo.koplugin"
CONFIG_PATH = f"{PLUGIN_FOLDER}/calibretypo/config.lua"
_VERSION_RE = re.compile(r'return\s+"([^"]+)"')


def plugin_version(plugin_dir: Path) -> str:
    source = (plugin_dir / "calibretypo" / "version.lua").read_text()
    match = _VERSION_RE.search(source)
    return match.group(1) if match else "unknown"


def _lua_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    # Lua rejects raw line breaks. 3 digits so a following digit isn't absorbed
    escaped = re.sub(r"[\x00-\x1f\x7f]", lambda m: f"\\{ord(m.group()):03d}", escaped)
    return f'"{escaped}"'


def render_config(server_url: str, token: str, device_name: str) -> str:
    return (
        "-- Generated by the calibre-typo server for this device.\n"
        "-- Settings changed on the device take precedence over these.\n"
        "return {\n"
        f"    server = {_lua_string(server_url)},\n"
        f"    token = {_lua_string(token)},\n"
        f"    device_name = {_lua_string(device_name)},\n"
        "}\n"
    )


def build_zip(plugin_dir: Path, server_url: str, token: str, device_name: str) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(plugin_dir.rglob("*")):
            if path.is_file() and path.name != "config.lua":
                archive.write(path, f"{PLUGIN_FOLDER}/{path.relative_to(plugin_dir).as_posix()}")
        archive.writestr(CONFIG_PATH, render_config(server_url, token, device_name))
    return buffer.getvalue()
